NAME		= Sully
CC			= clang
CFLAGS		= -Wall -Wextra

SRC			= $(NAME).c

PHONY: all clean fclean re

all: $(NAME)

$(NAME):
	$(CC) $(CFLAGs) $(SRC) -o $(NAME)

clean:
 

fclean: clean
	rm -f $(NAME)

re: fclean all
